---
- name: Include distribution-specific variables
  include_vars: "{{ version_specific_vars_file }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"      # e.g. Ubunutu-16.04.yml, Ubunutu-18.10.yml
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"   # e.g. RedHat-6.yml, RedHat-7.yml, Debian-9.yml
        - "{{ ansible_os_family }}.yml"                                            # e.g. RedHat.yml, Debian.yml
      skip: true
  loop_control:
    loop_var: version_specific_vars_file
- include_tasks: "tasks/{{ ansible_os_family }}.yml"
