---
- include_vars: "vars/{{ ansible_os_family }}.yml"

- name: Ensures the required nfs share groups exist on the server
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    system: "{{ item.system|default(false) }}"
  with_items:
    - "{{ nfs_groups }}"

- name: Ensures the required nfs share owners exist on the server
  user:
    name: "{{ item.name }}"
    group: "{{ item.name }}"
    append: true
    uid: "{{ item.uid }}"
    system: "{{ item.system|default(false) }}"
    shell: "{{ item.shell|default(path_to_nologin) }}"
    create_home: "{{ not (item.system|default(false)) }}"
  with_items:
    - "{{ nfs_users }}"

- name: Add users to secondary groups
  user:
    name: "{{ item.user }}"
    group: "{{ item.user }}"
    groups: "{{ item.secondary_group }}"
    append: true
  with_items:
    "{{ nfs_secondary_groups }}"
