---
- name: Include distribution-specific variables
  include_vars: "{{ version_specific_vars_file }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"      # e.g. Ubunutu-16.04.yml, Ubunutu-18.10.yml
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"   # e.g. RedHat-6.yml, RedHat-7.yml, Debian-9.yml
        - "{{ ansible_os_family }}.yml"                                            # e.g. RedHat.yml, Debian.yml
      skip: true
  loop_control:
    loop_var: version_specific_vars_file

- name: Install packages
  include_tasks: "tasks/{{ ansible_os_family }}.yml"

- name: Check if mount point exists for NFS client
  stat:
    path: "{{ nfs_client_share_mount_point }}"
  register: stat_nfs_mountpoint
  when: nfs_client_create_fstab_entry == true

- name: Create fstab entry for NFS client
  mount:
    name: "{{ nfs_client_share_mount_point }}"
    src: "{{ nfs_host }}:{{ nfs_client_remote_export }}"
    fstype: nfs
    opts: "{{ nfs_client_mount_opts }}"
    state: mounted
  when: nfs_client_create_fstab_entry == true
    and stat_nfs_mountpoint.stat.exists == true
