---
- name: Create the share path {{ item.path }}
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    recurse: true
  with_items:
    - "{{ nfs_shares }}"

- name: Export the NFS share for {{ item.path }}
  lineinfile:
    dest: /etc/exports
    line: "{{ item.path }} {{ item.allow_from }}(rw,sync,no_subtree_check)"
    state: present
    create: yes
    backup: yes
  notify: restart nfs
  with_items:
    - "{{ nfs_shares }}"
